server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user:8082
          predicates:
            - Path=/usuarios/**
        - id: room-service
          uri: http://room:8082
          predicates:
            - Path=/salas/**
        - id: booking-service
          uri: http://booking:8082
          predicates:
            - Path=/reservas/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - 'http://localhost:3000'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            allowCredentials: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
